### PR TITLE
Provide a mechanism to automatically select the number of available processors

### PR DESCRIPTION
**Pull request by archmageirvine**
In the construction of `CombinedFactorAlgorithm` allow a thread count of 0 to mean, select as many processors as available.

### CODE REVIEW

**Comment by TilmanNeumann** [comment]
Something like this would be useful, but there is a minor issue with it: Runtime.getRuntime().availableProcessors() returns the number of threads, not the number of physical cores. But for the factorization of pretty large numbers it is faster to use less threads because they compete for memory access. So on my Ryzen 3900X for numbers like 350 bit or bigger I found it better to use just the number of physical cores. Unfortunately I am not aware of any method to get that number reliably from Java.

**Comment by TilmanNeumann** [comment]
Clearification on "compete for memory access": L3 cache is the crucial resource here

**Comment by archmageirvine** [comment]
I agree with your comments, especially if you are targeting harder numbers. The idea here is to try was to provide some moderately sensible value when the caller does not know an appropriate value to use.  In reality there could be lots of reasons why any particular number would not be ideal at a given time -- invariably I have other CPU process running on my machines.  Perhaps something like `(Runtime.getRuntime().availableProcessors()+1)/2` might be a reasonable compromise.

I'm happy for you to just close this and I will deal with it in my calling application.

**Comment by TilmanNeumann** [comment]
Yes I will close it. I know there are processors with 4 threads per core and others may not be using SMT at all.

**Pull request closed without merging**
